name: Accessible Tooltip
author: mashalla
category: Widgets
tags: [dialog, tooltip, modal, window, alert, confirm]
#docs: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
demo: http://www.accessiblemootoolsdemo.iao.fraunhofer.de/Mootools_Widgets/index.html
current: 1.3

sources:
  - "Source/tooltip.js"
  - "Source/demo.js"